import type { GameId } from '../engine/index.ts';

/** One hand category: P(on the deal) and P(final hand under perfect play). */
export interface OddsCategoryRow {
  key: string;
  label: string;
  dealt: number;
  perfect: number;
}

/** A canonical hold ("4 to a Royal") and its exact draw odds for each category it's listed under. */
export interface OddsDraw {
  label: string;
  /** Example dealt hand, e.g. "As Ks Qs Js 3d" (parse with `parseHand`). */
  hand: string;
  /** The first `hold` cards of `hand` are held. */
  hold: number;
  targets: string[];
  /** Category key → P(final hand in that category | this hold). */
  odds: Record<string, number>;
}

export interface GameOdds {
  gameId: GameId;
  categories: OddsCategoryRow[];
  draws: OddsDraw[];
}

/**
 * Exact hand odds per game (src/odds/<id>.json), generated by `npm run odds` from src/engine/odds.ts.
 * Never compute or edit these in the UI.
 */
const modules = import.meta.glob('../odds/*.json', { eager: true }) as Record<string, { default: GameOdds }>;

export const ODDS_BY_GAME: Partial<Record<GameId, GameOdds>> = Object.fromEntries(
  Object.values(modules).map((mod) => [mod.default.gameId, mod.default]),
) as Partial<Record<GameId, GameOdds>>;

/** "1 in 40,170" style; "—" when impossible. */
export function oneIn(p: number): string {
  if (p <= 0) return '—';
  const n = 1 / p;
  // One decimal under 100 ("1 in 23.5"), dropping a ".0" ("1 in 47"); whole numbers above.
  return `1 in ${n < 100 ? n.toFixed(1).replace(/\.0$/, '') : Math.round(n).toLocaleString('en-US')}`;
}
