import type { GameId } from '../engine/index.ts';
import data from '../bankroll/risk.json';

/**
 * Exact bankroll-survival results (D14), generated by `node scripts/bankroll-risk.ts` into
 * src/bankroll/risk.json. Read-only here: never recompute or hand-edit these numbers in the UI.
 */
export interface RiskHorizon {
  hands: number;
  expectedLossBets: number;
  sdOfResultBets: number;
  /** Keyed by survival target as a string: "0.9", "0.95", "0.99". */
  bankrollNeededBets: Record<string, number>;
}

export interface RiskPerError {
  errorRate: number;
  /** Return with this error rate (fraction). */
  return: number;
  sdPerHandBets: number;
  horizons: RiskHorizon[];
}

export interface RiskGame {
  gameId: GameId;
  name: string;
  returnBest: number;
  perError: RiskPerError[];
}

export interface RiskData {
  errorRates: number[];
  horizons: number[];
  targets: number[];
  denominationsCents: number[];
  games: RiskGame[];
}

export const RISK: RiskData = data as unknown as RiskData;

export const COINS_PER_BET = 5;

export const riskFor = (gameId: GameId): RiskGame | undefined => RISK.games.find((g) => g.gameId === gameId);

/** The error-rate column closest to `rate` (fraction, e.g. 0.012 → 0.01), for "your error rate". */
export function nearestErrorRate(rate: number): number {
  return RISK.errorRates.reduce((best, e) => (Math.abs(e - rate) < Math.abs(best - rate) ? e : best), RISK.errorRates[0]);
}

/** Bankroll needed in bets, or undefined if that combination isn't in the data. */
export function bankrollBets(gameId: GameId, errorRate: number, hands: number, target: number): number | undefined {
  const pe = riskFor(gameId)?.perError.find((p) => p.errorRate === errorRate);
  return pe?.horizons.find((h) => h.hands === hands)?.bankrollNeededBets[String(target)];
}

/** Bets → cents at a denomination (dollars per coin), max bet. */
export const betsToCents = (bets: number, denomination: number): number =>
  bets * COINS_PER_BET * Math.round(denomination * 100);
