/**
 * Generates a strategy chart from exact EVs and measures it against perfect play.
 *
 *   npm run chart -- nsud
 *
 * Writes src/charts/<id>.json (for the app) and docs/charts/<id>.md (readable chart).
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { handToString } from '../src/engine/cards.ts';
import { buildTables } from '../src/engine/ev.ts';
import { GAMES, type GameId } from '../src/engine/games.ts';
import { canonicalHands, deucesPattern, deucesSection, generateChart } from '../src/engine/strategy.ts';

const id = (process.argv[2] ?? 'nsud') as GameId;
const game = GAMES[id];
if (!game) throw new Error(`unknown game ${id}`);
if (!game.rows.some((r) => r.key === 'four-deuces')) throw new Error('only deuces-wild charts are supported so far');

const t0 = performance.now();
const tables = buildTables(game);
const hands = canonicalHands();
const chart = generateChart(tables, deucesPattern, deucesSection, hands);
const secs = ((performance.now() - t0) / 1000).toFixed(1);

const pct = (x: number, d = 2) => `${(x * 100).toFixed(d)}%`;
const md: string[] = [
  `# ${game.name}: strategy chart`,
  '',
  `Generated by \`npm run chart -- ${id}\` from exact EVs over all 2,598,960 starting hands. Do not edit by hand.`,
  '',
  `- Perfect play: **${pct(chart.perfectReturn, 4)}**`,
  `- Following this chart: **${pct(chart.chartReturn, 4)}** (gives up ${pct(chart.perfectReturn - chart.chartReturn, 4)})`,
  `- Hands where the chart is not optimal: ${pct(chart.errorRate, 3)}`,
  '',
  'Always hold every deuce. Find the section for the number of deuces you were dealt, then play the **first** line you can make.',
  '',
];
for (const s of chart.sections) {
  md.push(`## ${s.section === 1 ? '1 deuce' : `${s.section} deuces`} dealt (${pct(s.share)} of hands)`, '');
  md.push('| # | Hold | Used | Example |', '|---|---|---|---|');
  s.lines.forEach((l, i) => md.push(`| ${i + 1} | ${l.label} | ${pct(l.share, 1)} | \`${handToString(l.example)}\` |`));
  md.push('');
}
md.push('## Chart mistakes by type', '', '| Chart says | Better | Hands | EV given up |', '|---|---|---|---|');
for (const g of chart.errorGroups.slice(0, 20)) md.push(`| ${g.chartLabel} | ${g.bestLabel} | ${pct(g.share, 3)} | ${pct(g.evLost, 4)} |`);
md.push('');
md.push('## Where the chart is wrong (largest EV cost × frequency)', '', '| Hand | Chart says | Better | Cost (bets) |', '|---|---|---|---|');
for (const e of chart.worstErrors.slice(0, 25)) md.push(`| \`${handToString(e.hand)}\` | ${e.chartLabel} | ${e.bestLabel} | ${e.cost.toFixed(4)} |`);

mkdirSync('src/charts', { recursive: true });
mkdirSync('docs/charts', { recursive: true });
writeFileSync(`src/charts/${id}.json`, JSON.stringify(chart, null, 1));
writeFileSync(`docs/charts/${id}.md`, md.join('\n') + '\n');
console.log(`${id}: perfect ${pct(chart.perfectReturn, 4)}, chart ${pct(chart.chartReturn, 4)}, chart errors on ${pct(chart.errorRate, 3)} of hands, ${chart.sections.reduce((n, s) => n + s.lines.length, 0)} lines (${secs}s)`);
